### ISSUE TITLE
Tip: Make sure your virtualenv pip isn't _really_ old

### ISSUE THREAD

**Issue by jheasly** [california-civic-data-coalition/first-python-notebook#1]
Hi!
Using OS X 10.11.6 El Capitan here. For whatever reason, my virtualenv had a _really_ old version of pip (1.4.1) and when I tried
```bash
$ pip install jupyter
```
I ended up with this error:
```bash
 ... [snip] ... 

Downloading/unpacking ipython (from jupyter-console->jupyter)
  Downloading ipython-5.2.2.tar.gz (4.9MB): 4.9MB downloaded
  Running setup.py egg_info for package ipython
    error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"
    Complete output from command python setup.py egg_info:
    error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/ ... 

... [snip] ... 

```
So following the [jupyter install advice](http://jupyter.org/install.html), I upgraded my pip 
```bash
$ pip install --upgrade pip
```
I went from 1.4.1 to 9.0.1 (!) and then `pip install jupyter` worked like a charm!  
So if at NICAR you see an install bomb like the above, try upgrading the virtualenv pip.

**Comment by palewire** [comment]
v1 to v9! Quantum leap!

![](https://media.giphy.com/media/z8msYyccu5MFq/giphy.gif)

**Comment by jheasly** [comment]
For sure. Really weird. I made that virtualenv last summer ...  
And I'd never been able to get the non-anaconda/pip way to work! So glad I got it going! Your tutorial's to blame! Huzzah!
