### ISSUE TITLE
Add disclaimer about Python3?

### ISSUE THREAD

**Issue by zstumgoren** [california-civic-data-coalition/first-python-notebook#27]
Hey Ben,
This is great stuff. I just ran through the tutorial to see how it would fare on Python 3, and happy to report that every single command worked!  Wondering if it's worth posting a little heads up in the [Python prerequisites section](http://www.firstpythonnotebook.org/prerequisites/python.html) noting as much, so folks know they can use either 2.x or 3.x (note I tested on Python 3.6.1). Totally understand if you don't want to tie yourself to maintaining both versions, btw, so no stress if you want to keep the focus on 2.7.

Cheers!

Serdar

**Comment by zstumgoren** [comment]
Also, the handful of installs (jupyter ,pandas and matplotlib) also work with pipenv, fwiw

**Comment by palewire** [comment]
Great. Thanks for the note. I think would be a good update to make.

I'm aiming to revise this class for the upcoming NICAR here in California.
If you have any larger thoughts on how it could improve, please let me know.

**Comment by zstumgoren** [comment]
Excellent! I'll hit you up offline or in another Issue with thoughts as they arise, but so far, it looks like a great intro to both campfin and data wrangling. Nicely done sir!
