### ISSUE TITLE
Explicitly encourage and teach Python 3

### ISSUE THREAD

**Issue by simonw** [california-civic-data-coalition/first-python-notebook#30]
https://pythonclock.org/ says Python 2.7 will retire in 1 Month, 10 Days, 4 Hours, 56 Minutes and 49 Seconds

More to the point: this is one of the best tutorials on getting a Python development environment set up I've ever seen, but I want people to get going with Python 3 so they can use my [Datasette](https://github.com/simonw/datasette) project!

I imagine updating it to Python 3 is not an insignificant amount of work, due to the need to re-record the installation videos. But I'm optimistically filing a bug report anyway!

**Comment by palewire** [comment]
The plan is rewrite the class with Python 3 and Altair for NICAR 2020!

**Comment by simonw** [comment]
Awesome!
