### ISSUE TITLE
jupyter lab install

### ISSUE THREAD

**Issue by cephillips** [california-civic-data-coalition/first-python-notebook#33]
You may get this error:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/jupyterlab_launcher-0.11.2.dist-info'
Consider using the `--user` option or check the permissions.

That’s because of the permissions you have on your computer.. (note this error will likely occur if you are on a mac. 
https://github.com/jupyterlab/jupyterlab/issues/3913

Try using this command: pip install --user jupyterlab
Q: Should we just suggest this for everyone?

**Comment by palewire** [comment]
We're going to switch to Jupyter Desktop to obviate this.
