### ISSUE TITLE
latest jupyter didn't default to 'code' edit mode

### ISSUE THREAD

**Issue by epu** [california-civic-data-coalition/first-python-notebook#46]
When running through the tutorial on my own, in `Hello Notebook` section `Write Python in the notebook`, I had to switch the new notebook's editing mode to `Code` in a dropdown before math worked.

I went to make edits and rebuild them from source, but yolk was confused because both yolk and yolk3k were installed into a python3 pipenv.

I have fixes for both of these, but I'm not sure how you'd prefer to handle these, and I'm not a professional writer targeting new folks, so the tone of my PR is maybe not what you would prefer.

**Comment by palewire** [comment]
I am fixing the Pipfile now.
